version: '3'
services: 
  redis:
    image: redis:3.2-alpine
    command: redis-server --appendonly yes --requirepass nbook_redis
    volumes:
      - nbook-redis:/data
    networks:
      - docker_nbook
    # ports:
    #   - 6379:6379

  mysql:
    image: 'mysql/mysql-server:5.7'
    container_name: mysql
    environment:
      MYSQL_DATABASE: "nbook"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "12345678"
      MYSQL_ROOT_PASSWORD: "12345678"
    volumes:
      - ./init.d/mysql:/docker-entrypoint-initdb.d
      - nbook-mysql:/var/lib/mysql
    networks:
      - docker_nbook
    ports:
      - '6603:3306'

  nbook-egg:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - env=value
    volumes:
      - ./logs/docker:/root/logs/nbook-egg
      - ./app/public/upload:/usr/src/app/app/public/upload
    environment:
      - NODE_ENV=production
      - EGG_SERVER_ENV=prod
      - EGG_REDIS_DB=0
      - NBOOK_REDIS_HOST=redis
      - NBOOK_REDIS_PORT=6379
      - NBOOK_REDIS_PASSWORD=nbook_redis
      - NBOOK_MYSQL_HOST=mysql
      - EGG_MINI_ASSETS=true
      # - EGG_SITE_STATIC_HOST=${EGG_SITE_STATIC_HOST}
    depends_on:
      - redis
      - mysql
    networks:
      - docker_nbook
    ports:
      - 7001:7001
    command: ["npm", "run", "docker"]

volumes:
  nbook-redis:
  nbook-mysql:

networks:
  docker_nbook:
    driver: bridge